name: submit-azure-machine-learning-job

trigger:
- none

variables:
  service-connection: 'Service-Connection-mlp-sit-resource-manager' # replace with your service connection name
  resource-group: 'sae-mlp-sea-rg' # replace with your resource group name
  workspace: 'kw-exp' # replace with your workspace name

jobs:
- job: SubmitAzureMLJob
  displayName: Submit AzureML Job
  timeoutInMinutes: 300
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: UsePythonVersion@0
    displayName: Use Python >=3.8
    inputs:
      versionSpec: '>=3.8'

  - bash: |
      set -ex

      az version
      az extension add -n ml
    displayName: 'Add AzureML Extension'

  - task: AzureCLI@2
    name: submit_azureml_job_task
    displayName: Submit AzureML Job Task
    inputs:
      azureSubscription: $(service-connection)
      workingDirectory: 'cli/jobs/pipelines-with-components/nyc_taxi_data_regression'
      scriptLocation: inlineScript
      scriptType: bash
      inlineScript: |
      
        # create pipeline-draft
        az ml pipeline create-draft --experiment_name 'test' --name 'nyc_taxi_data_regression_single_job' --pipeline-yaml single-job-pipeline.yml -g $(resource-group) -w $(workspace)

        # # submit component job and get the run name
        # job_name=$(az ml job create --file single-job-pipeline.yml -g $(resource-group) -w $(workspace) --query name --output tsv)

        # # publish job and set as default
        # az ml pipeline publish -w $(workspace) 

        # # Set output variable for next task
        # echo "##vso[task.setvariable variable=JOB_NAME;isOutput=true;]$job_name"